version: "1.1"
name: "aws-s3-connector"
description: "This connector provides apis to interact with AWS S3 bucket"
springConfigurationClass: "com.wavemaker.connector.configuration.S3ConnectorConfiguration"
